name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-BE:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      working-directory: ./Backend
      run: npm install

    - name: Execute tests
      working-directory: ./Backend
      run: npm run test

    - name: Compress coverage folder
      run: zip -r coverage-be.zip Backend/coverage

    - name: Upload test artifact
      uses: actions/upload-artifact@v2
      with:
        name: Test-artifact
        path: test-be.zip

  build-BE:
    runs-on: ubuntu-latest
    needs: test-BE

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./Backend
        run: npm install

      - name: Compress build folder
        run: zip -r build-be.zip Backend/

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build-artifact
          path: build-be.zip

  test-FE:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      working-directory: ./Backend
      run: npm install
    
    - name: Install dependencies
      working-directory: ./Frontend
      run: npm install
    
    - name: Start Backend
      working-directory: ./Backend
      run: npm run start

    - name: Start Frontend
      working-directory: ./Frontend
      run: npm run start

  build-FE:
    runs-on: ubuntu-latest
    needs: test-FE

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Build FE
        working-directory: ./Frontend
        run: npm run build

      - name: Compress build folder
        run: zip -r build-fe.zip Frontend/build/

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build-artifact
          path: build-fe.zip