name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      working-directory: ./Backend
      run: npm install

    - name: Execute tests
      working-directory: ./Backend
      run: npm run test

    - name: Compress coverage folder
      run: zip -r coverage.zip Backend/coverage

    - name: Upload test artifact
      uses: actions/upload-artifact@v2
      with:
        name: Test-artifact
        path: coverage.zip

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Compress build folder
        run: zip -r build.zip ./

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build-artifact
          path: build.zip